#!/bin/sh

#---------------------------------------------------------------------------
# Compile and link the f90 tools.
#---------------------------------------------------------------------------

   system=`uname`
   echo system = $system

   ##################################
   #
   # Intel Linux NAGware F95
   #
   if [ $system = 'Linux' ] ; then
      f95 -o f90deps f90deps.f90
      rm -f *.mod *.MOD

   ##################################
   #
   # Other systems?..
   #
   else
      f90 -o f90deps f90deps.f90
      rm -f *.mod *.MOD
   fi
